### ISSUE TITLE
[Question] Are the graphs executable?

### ISSUE THREAD

**Issue by rraallvv** [aphex-/BrotherhoodOfNode#2]
I read the post in the Indi Dev Group at Facebook and wanted to ask whether you are planning to make the graphs executable from within the game?

**Comment by aphex-** [comment]
Hello rraallvv and thank you for the interest. The editor itself will not be something to use in a game. You can use the events and the graph data structure to e.g compose a material in your scene or something. 
Dont get me wrong.. BrotherhoodOfNode only offers you the graph related stuff. What you want to do with it depends on your implementation.
(You can implement real-time manipulation of your scene in edit mode If you use Unities [ExecuteInEditMode] annotation in your code.)

**Comment by rraallvv** [comment]
Hi @aphex-, I’ve been looking around for something to run data-flow and flow-based-programs in games, and found a couple of libraries that could be used to run the graphs generated by BoN. It’s good to have something like BoN as a FOSS project. Thanks for your reply.

**Comment by aphex-** [comment]
You are welcome. If you build up something using BoN let me know.
