### ISSUE TITLE
Pretty good but kind of limited! (but will try to add features my bro, your project is awesome)

### ISSUE THREAD

**Issue by KimsFerdy** [aphex-/BrotherhoodOfNode#9]
you can extend nodes (add as many nodes as you need,)
the only thing that annoyed me

1. Selection (node selection)
2. Runtime application, (could be good having an asset or prefab that hold the graph in scene)
3. C# binding (being able to access some exposed parameters from another script)
4. Save as Json is good (scriptable object could be more applicable)(but I can't complain)

Note: this is just my opinion, I'll try to give this project some times and try add some functionalities(if I can of course)

**Comment by realstaticvoid** [comment]
Thank you for the feedback.
